---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
args:
  MATTER_SERVER_VERSION: 1.0.7
  HOME_ASSISTANT_CHIP_VERSION: 2022.11.1
